### PR TITLE
Added Two Features for Community Engagement

### PR DESCRIPTION
**Pull request by its-sbal**
Worked on the issues #1  and added two features that i think can increase community engagement.

**Feature 1 : Audio Room**
A social audio room to allow more people to engage and share using their voice.

**Feature 2 : Virtual Space**
Members can attend live shows and talk with other people just like in real life.

### CODE REVIEW

**Comment by SawoCommunity** [comment]
Hi @its-sbal can you tell me why did you change the actual README.md of the repository?

**Comment by its-sbal** [comment]
Nothing, i was just experimenting on how github commit and differentiates.

**Comment by SawoCommunity** [comment]
> Nothing, i was just experimenting on how github commit and differentiates.

I think I have reverted it back to the original. Please refrain from changing the original README.md of the repository.

**Comment by its-sbal** [comment]
Okay, is the problem solved ? OR i have to create another repository and
then PR

**Comment by SawoCommunity** [comment]
Yeah! Now the problem is solved.

**Pull request merged**
